# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoQR', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=4, null=True, unique=True)),
                ('Cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Cliente')),
            ],
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='idCliente',
            new_name='nroEntradas',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='idLugar',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='idEvento',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='idSector',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='aprobada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='codigoQR',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='idPrecio',
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Categoria'),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Lugar'),
        ),
        migrations.AddField(
            model_name='precio',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Evento'),
        ),
        migrations.AddField(
            model_name='precio',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Sector'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precioTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sector',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Lugar'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='precio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Precio'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Reserva'),
        ),
    ]
