# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_auto_20161102_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, null=True, unique=True)),
                ('documento', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pin',
            name='Cliente',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Telefono'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='pin',
            name='telefono',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.Telefono'),
        ),
    ]
