# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('mapaLugar', models.CharField(max_length=50, null=True)),
                ('campoPrueba', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
